SHOW CATALOGS;
CREATE CATALOG IF NOT EXISTS marathos;

USE CATALOG marathos;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

CREATE VOLUME IF NOT EXISTS raw;


